language: node_js
node_js:
  - "8.12.0"
cache:
  directories:
  - html-src/node_modules
script:
  - cd html-src && npm install && npm run build
after_failure: cat /home/travis/.npm/_logs/*-debug.log
warnings_are_errors: false
env:
  CI=false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: html-src/build
  on:
    branch: master
